# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Advisor_V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'
  pod 'AlamofireImage'
  pod 'lottie-ios'
  # Pods for Advisor_V2

end
